### PR TITLE
tailwindcss

### PR DESCRIPTION
**Pull request by niclimcy**

### CODE REVIEW

**Comment by niclimcy** [comment]
I migrated maybe half of the custom css classes with this PR, not sure if I should continue in a separate PR.

Current layout is similar enough to what it was originally.

**Comment by luk1337** [comment]
Does it make sense to keep history of your commits, or could we just squash it as one big "Rewrite CSS with Tailwind CSS"?

**Comment by niclimcy** [comment]
> Does it make sense to keep history of your commits, or could we just squash it as one big "Rewrite CSS with Tailwind CSS"?

git squash should be fine because most of the following commits were fixing initial commit issues

**Comment by luk1337** [comment]
ok yolo squashed

**Pull request merged**
