### PR TITLE
Restructure vue project

### PR DESCRIPTION
**Pull request by niclimcy**
TODO:

- [x] Regenerate vue app using vite create app
- [x] ESLint
- [x] Run prettier
- [x] Rename "Main" pages to "View" terminology
- [x] Move "Main" pages to View directory

### CODE REVIEW

**Comment by niclimcy** [comment]
Not sure if terser is still required, can consider removing if esbuild has been fixed

**Comment by luk1337** [comment]
> Not sure if terser is still required, can consider removing if esbuild has been fixed

look at why I used terser to begin with.

**Comment by niclimcy** [comment]
> > Not sure if terser is still required, can consider removing if esbuild has been fixed
> 
> look at why I used terser to begin with.

This https://github.com/lineageos-infra/updater-client/commit/1a0205a5b62a5c8bd5991edd48df69f652d6a022 but why? Does it minify shit wrongly?

**Comment by luk1337** [comment]
> > > Not sure if terser is still required, can consider removing if esbuild has been fixed
> > 
> > 
> > look at why I used terser to begin with.
> 
> This [1a0205a](https://github.com/lineageos-infra/updater-client/commit/1a0205a5b62a5c8bd5991edd48df69f652d6a022) but why? Does it minify shit wrongly?

I think this browser was just shit, but terser worked on it, so w/e.

**Comment by niclimcy** [comment]
> > > > Not sure if terser is still required, can consider removing if esbuild has been fixed
> > > 
> > > 
> > > look at why I used terser to begin with.
> > 
> > 
> > This [1a0205a](https://github.com/lineageos-infra/updater-client/commit/1a0205a5b62a5c8bd5991edd48df69f652d6a022) but why? Does it minify shit wrongly?
> 
> I think this browser was just shit, but terser worked on it, so w/e.

image
Works fine with esbuild minify on Pale Moon 32.5.2 ¯\_(ツ)_/¯

**Comment by luk1337** [comment]
> > > > > Not sure if terser is still required, can consider removing if esbuild has been fixed
> > > > 
> > > > 
> > > > look at why I used terser to begin with.
> > > 
> > > 
> > > This [1a0205a](https://github.com/lineageos-infra/updater-client/commit/1a0205a5b62a5c8bd5991edd48df69f652d6a022) but why? Does it minify shit wrongly?
> > 
> > 
> > I think this browser was just shit, but terser worked on it, so w/e.
> 
> image Works fine with esbuild minify on Pale Moon 32.5.2 ¯\_(ツ)_/¯

Tested this myself and it seems like Pale Moon fixed it. So for now I cherry-picked modified tenser removal commit straight to main.

**Comment by niclimcy** [comment]
Looks fine to me

**Pull request merged**
